package org.bnemu.core.auth;

/**
 * Authentication token for D2 realm connection.
 * Generated by BNCS when client requests realm login,
 * validated by D2CS when client connects.
 */
public class RealmToken {
    private final int cookie;
    private final String accountName;
    private final long createdAt;
    private final int clientToken;
    private final int serverToken;

    public RealmToken(int cookie, String accountName, int clientToken, int serverToken) {
        this(cookie, accountName, clientToken, serverToken, System.currentTimeMillis());
    }

    public RealmToken(int cookie, String accountName, int clientToken, int serverToken, long createdAt) {
        this.cookie = cookie;
        this.accountName = accountName;
        this.clientToken = clientToken;
        this.serverToken = serverToken;
        this.createdAt = createdAt;
    }

    public int getCookie() {
        return cookie;
    }

    public String getAccountName() {
        return accountName;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public int getClientToken() {
        return clientToken;
    }

    public int getServerToken() {
        return serverToken;
    }

    public boolean isExpired() {
        // Tokens expire after 5 minutes
        return System.currentTimeMillis() - createdAt > 5 * 60 * 1000;
    }
}
